### ISSUE TITLE
Installation instructions don't work

### ISSUE THREAD

**Issue by ned-pcs** [brainelectronics/Micropython-ESP-WiFi-Manager#30]
using micropython 1.10 on ESP32 with SPIRAM.

Tried both `upip` and `mip` (which is included in my micropython build).

Couldn't install `micropython-ulogging`.
```
>>> mip.install('micropython-ulogging')
Installing micropython-ulogging (latest) from https://micropython.org/pi/v2 to /lib
Package not found: https://micropython.org/pi/v2/package/6/micropython-ulogging/latest.json
Package may be partially installed
```

So manually installed `micropython-ulogging`.

Couldn't install `micropython-brainelectronics-helper`

So manually cloned the github repo and manually installed those files.

But some files are sill missing:
```
MPY: soft reboot
Traceback (most recent call last):
  File "boot.py", line 14, in <module>
  File "/lib/be_helpers/__init__.py", line 6, in <module>
  File "/lib/be_helpers/module_helper.py", line 10, in <module>
ImportError: no module named 'argparse'
Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "/lib/wifi_manager/__init__.py", line 4, in <module>
  File "/lib/wifi_manager/wifi_manager.py", line 35, in <module>
ImportError: no module named 'be_helpers.generic_helper'
MicroPython v1.20.0-117-ged7a3b11d on 2023-05-24; ESP32 module (spiram) with ESP32
Type "help()" for more information.
```

It appears that some files are missing from the `be_helpers` repo:
```
/home/ned/PCS/esp32> ls  /pyboard/lib/be_helpers
__init__.py      module_helper.py version.py  
```

Could you double-check the installation instructions and package index versions using a modern version of micropython (preferably using `mip`)?

**Comment by brainelectronics** [comment]
Should be resolved by:

- Package Validation changes:
  -  https://github.com/brainelectronics/micropython-package-validation/issues/4 and https://github.com/brainelectronics/micropython-package-validation/issues/6
  - https://github.com/brainelectronics/micropython-package-validation/pull/3 and https://github.com/brainelectronics/micropython-package-validation/pull/5
  - [package-validation 0.3.0](https://github.com/brainelectronics/micropython-package-validation/releases/tag/0.3.0)
- MicroPython Modules changes:
  - https://github.com/brainelectronics/micropython-modules/issues/20 and https://github.com/brainelectronics/micropython-modules/issues/21
  - https://github.com/brainelectronics/micropython-modules/pull/22
  - [micropython-modules 1.7.0](https://github.com/brainelectronics/micropython-modules/releases/tag/1.7.0)
- MicroPython ESP WiFi Manager changes:
  - [Release 1.7.0](https://github.com/brainelectronics/micropython-modules/releases/tag/1.7.0)

**Comment by ned-pcs** [comment]
Thanks! closing.
